import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar";

import SideBar from "@/components/SideBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBar />
        <div className="grid grid-cols-12 gap-4">
          <div className="col-span-2">
            <SideBar />
          </div>
          <div className="col-span-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
